tokenData:
  mobDrop:
    - "SILVERFISH:5:3"
  logDrop:
    - "LOG,0:5:3"
  blockDrop:
    - "STONE,0:5:3"
    # "Token_Source:Chance:Range (from 1 to the number you put)"
progressBar:
  bar: '----------'
  filledColor: '&a'
  unfilledColor: '&7'
toolsData:
  MOBSWORD:
    itemName: '&7MobSword'
    description:
      - '&7Cool Description'
    maxLevel: 100
    xpSource:
      - "ZOMBIE:5"
      - "SKELETON:10"
      - "SILVERFISH:20"

  POSEIDONS_AXE:
    itemName: '&bPoseidon''s Axe'
    description:
      - '&7Insane Poseidon Axe :)'
    maxLevel: 100
    xpSource:
      - "LOG,0:5"
      - "LOG,1:10"

  ATLANTIS_PICKAXE:
    itemName: '&bAtlantis Pickaxe'
    description:
      - '&7Cool Atlantis Pickaxe'
    maxLevel: 100
    xpSource:
      - "STONE:1"
      - "COAL_ORE:5"
      - "IRON_ORE:10"

itemsFormat:
  tokenFormat:
    material: NETHER_STAR
    displayName: '&6Upgrade Token'
    lore:
      - '&7Use this token to upgrade your &bPoseidonTools!'
  toolFormat:
    displayName: '%item-name%'
    lore:
      - '%item-description%'
      - ' '
      - '&7Level (&e%item-level%&7/&6%item-max-level%&7):'
      - '%progress-bar% &7(&e%item-xp%&7/&6%item-xp-needed%&7)'
  rageBerry:
    material: SPIDER_EYE
    displayName: "&cRage Berry"
    lore:
      - "&7Enter lore here :)"
  spiritOfTheWoods:
    material: POTION
    damage: 8201
    displayName: "&aSpirit Of The Woods"
    lore:
      - "&7Enter lore here :)"
  spicyTaco:
    material: RAW_BEEF
    displayName: "&cSpicy Taco"
    lore:
      - "&7Enter lore here 0-0"