name: PoseidonTools
main: me.chickenstyle.poseidontools.PoseidonTools
description: PoseidonTools
version: 1.0
author: ChickenStyle
commands:
  poseidontools:
    description: PoseidonTools Command
    aliases:
      - pd