tokenData:
  mobDrop:
    - SILVER_FISH:5
progressBar:
  bar: '----------'
  filledColor: '&a'
  unfilledColor: '&7'
toolsData:
  MOBSWORD:
    itemName: '&7MobSword'
    description:
      - '&7Cool Description'
    maxLevel: 100
    enchantmentMaxLevel: 100
    xpSource:
      - ZOMBIE:5
      - SKELETON:10
      - SILVERFISH:20
    enchantments:
      Token_Booster:
        upgradePrice: 5
        startingChance: 5
      Drop_Booster:
        upgradePrice: 5
        startingChance: 5
      Key_Finder:
        upgradePrice: 5
        startingChance: 5
      Spawner_Finder:
        upgradePrice: 5
        startingChance: 5
      XP_Finder:
        upgradePrice: 5
        startingChance: 5
      Immunity:
        upgradePrice: 5
        startingChance: 5
      Multi_Kill:
        upgradePrice: 5
        startingChance: 5
  POSEIDONS_AXE:
    itemName: '&bPoseidon''s Axe'
    description:
      - '&7Insane Poseidon Axe :)'
    maxLevel: 100
    enchantMaxLevel: 100
    xpSource:
      - LOG,0:5
      - LOG,1:10
    enchantments:
      Efficiency:
        upgradePrice: 5
        startingChance: 5
      Token_Booster:
        upgradePrice: 5
        startingChance: 5
      Drop_Booster:
        upgradePrice: 5
        startingChance: 5
      Key_Finder:
        upgradePrice: 5
        startingChance: 5
      Spawner_Finder:
        upgradePrice: 5
        startingChance: 5
      Speed:
        upgradePrice: 5
        startingChance: 5
  ATLANTIS_PICKAXE:
    itemName: '&bAtlantis Pickaxe'
    description:
      - '&7Cool Atlantis Pickaxe'
    maxLevel: 100
    enchantMaxLevel: 100
    xpSource:
      - STONE:1
      - COAL_ORE:5
      - IRON_ORE:10
    enchantments:
      Token_Booster:
        upgradePrice: 5
        startingChance: 5
      Drop_Booster:
        upgradePrice: 5
        startingChance: 5
      Key_Finder:
        upgradePrice: 5
        startingChance: 5
      Spawner_Finder:
        upgradePrice: 5
        startingChance: 5
      Haste:
        upgradePrice: 5
        startingChance: 5
itemsFormat:
  tokenFormat:
    material: NETHER_STAR
    displayName: '&6Upgrade Token'
    lore:
      - '&7Use this token to upgrade your &bPoseidonTools!'
  toolFormat:
    displayName: '%item-name%'
    lore:
      - '%item-description%'
      - ' '
      - '&7Level (&e%item-level%&7/&6%item-max-level%&7):'
      - '%progress-bar% &7(&e%item-xp%&7/&6%item-xp-needed%&7)'
